//Auth Types
export const IS_LOADING='IS_LOADING'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILED='LOGIN_FAILED'
export const LOGIN_ATTEMPT="LOGIN_ATTEMPT"

//Events Type
export const SHOW_EVENTS='SHOW_EVENTS'
export const FETCH_EVENTS="FETCH_EVENTS"
export const FETCH_FAILED="FETCH_FAILED"
export const STOP_LOADING="STOP_LOADING"
